name: Manually Deploy to Heroku L

on: workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: "635c0a77-Of7f-458f-80d1-582fe21a86ef"
          heroku_app_name: "base22"
          heroku_email: "gokapon837@touchend.com"

          usedocker: true
          docker_heroku_process_type: web
          stack: "container"
          region: "eu"
